languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Alexander Gamerdinger"
# logo = "img/logo.jpg"
description = "Personal Website of Alexander Gamerdinger"
copyright = "&copy; 2023 Alexander Gamerdinger"

dateFormat = "2 January 2006"

[author]
  name = "Alexander Gamerdinger"
  image = "author.jpg"
  headline = "PhD Fellow at Copenhagen Business School"
  bio = "I am a PhD Fellow at Copenhagen Business School."
  links = [
    { email = "mailto:aga.ioa@cbs.dk" },
    { github = "https://github.com/GamerdingerA" },
    { linkedin = "https://linkedin.com/in/alexander-gamerdinger" },
    { twitter = "https://twitter.com/GamerdingerA" },
    { link = "https://www.cbs.dk/en/research/departments-and-centres/department-of-organization/staff/agaioa" },
    { google = "https://scholar.google.com/citations?user=qstJ4-QAAAAJ&hl=en&oi=ao" },
  ]
