languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1


title = "Alexander Gamerdinger"
copyright = "&copy; 2025 Alexander Gamerdinger"

[params]
  description = "Personal Website of Alexander Gamerdinger"
  dateFormat = "2 January 2006"

[params.author]
  name = "Alexander Gamerdinger"
  image = "author.jpg"
  headline = "PhD Fellow at Copenhagen Business School"
  bio = "I am a PhD Fellow at Copenhagen Business School."
  links = [
    { email = "mailto:aga.ioa@cbs.dk" },
    { github = "https://github.com/GamerdingerA" },
    { linkedin = "https://linkedin.com/in/alexander-gamerdinger" },
    { twitter = "https://twitter.com/GamerdingerA" },
    { google = "https://scholar.google.com/citations?user=qstJ4-QAAAAJ&hl=en&oi=ao" },
    { link = "https://www.cbs.dk/en/research/departments-and-centres/department-of-organization/staff/agaioa" },
  ]
