
[[main]]
  name = "about"
  url = "/about/"
  weight = 20

[[main]]
  name = "research"
  url = "/research/"
  weight = 30
  
  [[main]]
  name = "teaching"
  url = "/teaching/"
  weight = 40

# [[main]]
#  name = "blog"
#  url = "/blog/"
#  weight = 50


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#  name = "Privacy"
#  pageRef = "privacy"
#  weight = 10

  
  
  
