---
title: "Research"
author: "Alexander Gamerdinger"
date: "2021-12-14"
showTableOfContents: yes
showDate: no
showReadingTime: no
slug: /research/
description: "My research is focused on professionals, algorithmic work and wellbeing-related
  issues"
---

This page provides an overview of my work in progress, peer-reviewed publications and reports I have co-authored. It also shows a selected collection of press and media articles I was mentioned in. 


## Work in progress 

### Moral Authority in Risk Assessments: How Professionals Shape the Algorithmization of Life Insurance

This article explores how actuaries and data scientists shape the integration of machine learning (ML) in life insurance by asserting distinct moral frameworks. Actuaries emphasize transparency and actuarial fairness, favoring traditional models for pricing risks, while resisting ML due to concerns about explainability and fairness in market settings under public scrutiny. Data scientists, on the other hand, embrace ML in claims prevention by employing technical fairness metrics to justify individualized interventions, particularly in less publicly visible contexts. The findings highlight that professional norms and market contexts significantly influence the uneven adoption of ML, with actuaries preserving traditional practices and data scientists advancing algorithmic approaches.

### The Realpolitik of AI Ethics Governance in the European Union 

This paper examines the dynamics of AI ethics governance in the European Union, focusing on how general ethical principles are translated into sector-specific guidelines, with a particular emphasis on the insurance industry. The findings reveal that the shift from horizontal to sectoral governance intensifies interest-group conflicts, as stakeholders with diverse priorities grapple with operationalizing abstract ethical principles like fairness and explainability. It highlights the pivotal role of hybrid expertise, where ethical and technical knowledge converge, and underscores the challenges in aligning ethical governance with realpolitik and sectoral realities. This research provides critical insights into the complexities of crafting actionable AI ethics guidelines in contentious, high-stakes sectors.

### Data is the new money: How data scientists gain authority in life insurance 

This study examines how data scientists become an increasingly important professional group that drives forth the behavioral insurance revolution in life insurance. In this paper, I investigate how data scientists adopt machine learning (ML) algorithms to drive claims prevention, and how this positions them as "new money professionals." The findings highlight that data scientists need to employ relational strategies, such as collaboration with health guides for domain expertise, strategic alliances with actuaries for financial validation, and governance specialists for compliance.This research underscores how an emerging professions must connect with multiple stakeholders to gain authority and drive forward the behavioral transformation. 

### From Risk Transfer to Risk Prevention: How field level dynamics shape AI innovation pathways

This paper examines the uneven adoption of AI innovations in the Danish life insurance sector, contrasting its limited use in individualizing pricing (risk transfer) with its broader success in preventing health risks (risk prevention). The findings highlight that risk prevention gained traction due to strong alignment of stakeholder values, including societal benefits and regulatory support, while risk transfer faced barriers such as concerns about fairness, uninsurability, and reputational risks. The study emphasizes the importance of field-level legitimacy and strategic coordination in fostering innovation pathways. It sheds light on how shared norms and coordinated actions shape the adoption of AI technologies in regulated industries.


## Peer-reviewed Publications

-   Gamerdinger, A., Just, S. N., & Lantz, P. M. V. (2023). Healthy transparency: Dynamic interrelations between credibility, transparency, and trust in the context of Danish public authorities' COVID-19 communication. Social Sciences & Humanities Open, 8(1), 100688.[Link](https://www.sciencedirect.com/science/article/pii/S2590291123002930)

## Non-peer-reviewed Publications

- Gamerdinger, A., & Holm, J. (2024). Ethical AI in Life and Non-Life Insurance: A Framework for Mapping Ethical Trade-Offs in AI Use. Copenhagen: Forsikring & Pension. [Link](https://fogp.dk/media/n23fabwb/ethical-ai-in-life-and-non-life-insurance-final-oktober-2024.pdf)
-   Birkjær, M., Gamerdinger, A., & El-Abd, S. (2021). Towards a Nordic Wellbeing Economy. Copenhagen: Nordisk Ministerråd, pp. 1-61. [Link](https://doi.org/10.6027/nord2021-049)
-   Gamerdinger, A., Rubio, A., & Kaats, M. (2020) Wellbeing in the age of COVID-19. Copenhagen: Happiness Research Institute, pp. 1-35. [Link](https://www.happinessresearchinstitute.com/covid-19)

## Press & media

- AI: Dilemma-kortlægning skal finde ”skjulte” etiske overvejelser [Forsikring & Pension](https://fogp.dk/politik/digitalisering-og-dataetik/kunstig-intelligens/ai-dilemma-kortlaegning-skal-finde-skjulte-etiske-overvejelser/)
- Da Sundhedsstyrelsen blev til Coronastyrelsen [Kommunikationsforum](https://www.kommunikationsforum.dk/artikler/Saadan-kommunikerede-SST-under-pandemien)
-   Who makes the rules for a Wellbeing Economy? [Wellbeing Economy Alliance](https://weall.org/who-makes-the-rules-for-a-wellbeing-economy)
-   Talk about happiness and home (in German) [Deutschlandfunk Nova](https://www.deutschlandfunknova.de/beitrag/wohnen-unser-traum-vom-eigenheim-lebt)
-   The Loneliness Pandemic [Wellbeing People](https://www.youtube.com/watch?v=P9lXf1QTjSM)
-   Why we need a common language for Wellbeing Economy? [Wellbeing Economy Alliance](https://weall.org/why-we-need-a-common-language-for-wellbeing-economy)
-   How has Covid-19 affected wellbeing across the world? [What Works Wellbeing](https://whatworkswellbeing.org/blog/how-has-covid-19-affected-wellbeing-across-the-world/)
-   The Germans and their homes (in German) [Frankfurter Allgemeine](https://www.faz.net/aktuell/wirtschaft/gluecks-studie-die-deutschen-lieben-ihre-haeuser-16255243.html)
